export const CATEGORIES = [
    "Other",
    "Technology",
    "Games",
    "Art & Design",
    "Music",
    "Film & video",
    "Publishing",
    "Food & Drinks",
    "Community",
    "Education",
    "Health",
    "Environment",
    "Sports",
  ];